<?php


class BN_Print extends BN\BN_Print
{
    public $top_menu = true;

}

class Ambar_App extends BN_App
{
    function bootstrap()
    {
        \Sparket\DB\Web::setDB(BN_DB_WEB::getInstance());

        parent::bootstrap(); // TODO: Change the autogenerated stub


    }
}