<?php

class products_products_prices extends products_products
{

    /** @var \App\Products\Product\Price $product_price */
    protected $product_price;
    function config_custom()
    {
        parent::config_custom(); // TODO: Change the autogenerated stub
        $this->getProductInfo();


    }



    function getPriceInfo($PPriceID = "", $ignore_error = false)
    {
        $PPriceID = $PPriceID? : $this->input['PPriceID'];

        if (!$PPriceID)
        {
            BN_Messages::messageAjax('El registro no existe [PPriceID].', 'error');
        }

        $this->product_price = new \App\Products\Product\Price($this->product, null, $PPriceID);

        if (!$this->product_price->getPPriceID() && $ignore_error == false)
        {
            BN_Messages::messageAjax('El registro no existe.', 'error');
        }

    }

    function cmd_prices()
    {

        $js = [];
        $view_data = [];

        $table = new \Novut\Tools\Tables\Table($this->FormID);
        $table->setClass('table');
        $table->addField('PPriceVolMin', 'Min', '20%');
        $table->addField('PPriceVolMax', 'Max', '20%');
        $table->addField('PPricePrice', 'Precio', '30%');
        $table->addField('PPriceCurrencyCode', 'Moneda', '20%');
        $table->addField('action', '', '1%')->setFilter();



        /** @var \App\Products\Product\Price $price */
        foreach (\App\Products\Product\Prices::list($this->product, (new \App\Products\Prices\PList())->loadDefault(true), (new \Novut\Core\Query())->setOrder('PPriceVolMin', 'ASC')) as $price)
        {
            $data = $price->export();
            $data['action'] = $table->context_menu()->getPlaceholder('PPriceID', $data['PPriceID'], ['ProductID' => $data['ProductID']]);
            $table->addRow($data);
        }

        $table->context_menu()->add_menu('Editar', $table->context_menu()->action('prices_edit'));
        $table->context_menu()->add_menu('Eliminar', $table->context_menu()->action('prices_delete'));

        $view_data['table'] = $table->getTable();

        BN_Responses::modal($this->views->load_render('products/prices/list', $this->view_data_presets($view_data)), "Precios", $js);
    }

    function cmd_prices_new()
    {
        $js = [];
        $view_data = [];
        $view_data['cmd']  = "prices_new_add";
        $this->FormID .= "PriceNew";

        $populate = new \Novut\UI\Forms\Populate($this->FormID);
        $populate->setValueHtml('PPriceCurrencyID', \BN_Currency::getCurrencyList());
        $populate->setSelect2('PPriceCurrencyID');

        $js[] = $populate->getJs();


        BN_Responses::modal($this->views->load_render('products/prices/form', $this->view_data_presets($view_data)), "Agregar Precio", $js);
    }

    function cmd_prices_new_add()
    {
        $this->FormID .= "PriceNew";

        $validation = \BN_Forms::validation($this->FormID);
        $validation->setRequiredField('PPriceVolMin');
        $validation->setRequiredField('PPricePrice');
        $validation->setRequiredField('PPriceCurrencyID');

        foreach (['PPriceVolMin', 'PPriceVolMax', 'PPricePrice'] as $ii)
        {
            $this->input[$ii] = \BN_Format::number_decimal_raw($this->input[$ii]);
        }

        $validation->validate($this->input);


        try {

            $price = new \App\Products\Product\Price($this->product, null);
            $price->setPPriceVolMin($this->input['PPriceVolMin']);
            $price->setPPriceVolMax($this->input['PPriceVolMax']);
            $price->setPPricePrice($this->input['PPricePrice']);
            $price->setPPriceCurrency(\BN_Currency::getCurrencyIDbyCode($this->input['PPriceCurrencyID']));
            $price->add();

        } catch (\Novut\Exceptions\Exception $e) {
            $e->display();
        }

        \App\Products\Product\Prices::syncDefault($this->product);


        BN_Responses::notification_success("Cambios Aplicados", BN_JSHelpers::route($this->ModuleUrl, ['cmd' => 'prices', 'ProductID' => $this->product->getProductID()]));

    }

    function cmd_prices_edit()
    {
        $this->getPriceInfo();

        $product_price = $this->product_price->export();
        $js = [];
        $view_data = [];
        $view_data['cmd']  = "prices_edit_save";
        $this->FormID .= "PriceEdit";

        $populate = new \Novut\UI\Forms\Populate($this->FormID);

        $populate->setValueText('PPriceID', $this->product_price->getPPriceID());

        $populate->setValueHtml('PPriceCurrencyID', \BN_Currency::getCurrencyList());
        $populate->setValueSelect('PPriceCurrencyID', $this->product_price->getPPriceCurrencyCode());
        $populate->setSelect2('PPriceCurrencyID');

        $populate->setMultipleValueText(['PPriceVolMin', 'PPriceVolMax', 'PPricePrice'], $product_price);

        $js[] = $populate->getJs();


        BN_Responses::modal($this->views->load_render('products/prices/form', $this->view_data_presets($view_data)), "Editar Precio", $js);
    }

    function cmd_prices_edit_save()
    {
        $this->getPriceInfo();
        $this->FormID .= "PriceEdit";

        $validation = \BN_Forms::validation($this->FormID);
        $validation->setRequiredField('PPriceVolMin');
        $validation->setRequiredField('PPricePrice');
        $validation->setRequiredField('PPriceCurrencyID');

        foreach (['PPriceVolMin', 'PPriceVolMax', 'PPricePrice'] as $ii)
        {
            $this->input[$ii] = \BN_Format::number_decimal_raw($this->input[$ii]);
        }

        $validation->validate($this->input);


        try {

            $price = new \App\Products\Product\Price($this->product, null, $this->product_price->getPPriceID());
            $price->setPPriceVolMin($this->input['PPriceVolMin']);
            $price->setPPriceVolMax($this->input['PPriceVolMax']);
            $price->setPPricePrice($this->input['PPricePrice']);
            $price->setPPriceCurrency(\BN_Currency::getCurrencyIDbyCode($this->input['PPriceCurrencyID']));
            $price->save();

        } catch (\Novut\Exceptions\Exception $e) {
            $e->display();
        }

        \App\Products\Product\Prices::syncDefault($this->product);


        BN_Responses::notification_success("Cambios Aplicados", BN_JSHelpers::route($this->ModuleUrl, ['cmd' => 'prices', 'ProductID' => $this->product->getProductID()]));
    }

    function cmd_prices_delete()
    {
        $this->getPriceInfo();

        if (!$this->input['confirm'])
        {
            \BN_Responses::confirm_quick("&iquest;Deseas eliminar este registro?", 'confirm');
        }

        $price = new \App\Products\Product\Price($this->product, null, $this->product_price->getPPriceID());
        $price->cancel();

        \App\Products\Product\Prices::syncDefault($this->product);

        BN_Responses::notification_success("Cambios Aplicados", BN_JSHelpers::route($this->ModuleUrl, ['cmd' => 'prices', 'ProductID' => $this->product->getProductID()]));
    }

}