<?php

class products_products_gallery extends products_products
{
    function config_custom()
    {
        parent::config_custom(); // TODO: Change the autogenerated stub
        $this->getProductInfo();
    }

    function cmd_gallery()
    {
        $this->FormID .= "Gallery";
        $this->view_data["cmd"]       = "gallery_save";
        $this->view_data["ProductID"] = $this->input["ProductID"];
        $this->view_data["ProductGallery"] = json_decode($this->ProductInfo["ProductGallery"]);

        $this->response->modal($this->views->load_render('products/gallery', $this->view_data_presets($this->view_data)), 'Galer&iacute;a', $this->JS)->setWidth(800)->render();

        //BN_Responses::alert_success('Galeria de productos');
    }

    function cmd_gallery_save()
    {
        $this->FormID .= "Gallery";

        if (!$_FILES["ProductImage"]["name"])
        {
            $this->response->alert_error("No se detect&oacute;o ninguna imagen")->render();
        }

        $ext = array ("jpg", "png", "jpeg", "JPG", "PNG", "JPEG");

        $type = explode('/', $_FILES["ProductImage"]["type"]);
        $type = end($type);

        if(!in_array($type, $ext))
        {
            $this->response->alert_error('Formatos v&aacute;lidos : '.implode(', ', $ext). ".")->render();
        }

            // files
            $image_file = new \Novut\Tools\Files\S3;
            $image_file->setBucket('gbag-public');
            $image_file->setAsPublic();
            $image_file->setFileContent(file_get_contents($_FILES['ProductImage']['tmp_name']));
            $image_file->setFileName("products/product".$this->ProductInfo["ProductID"]."_".date('YmdHis'));
            $url = $image_file->push();

            print_r($url);
            exit;

            // todo remove simular una url, despues remover


            $images = $this->input["images"];
            if($url)
            {
                $images[count($images)] = $url;
            }

            $images = json_encode($images);

            $this->db->Update($this->tables['products'], ["ProductGallery" => $images], 'ProductID', $this->ProductInfo['ProductID']);

            $this->response->alert_success("Cambios Aplicados", 'reload')->render();
    }
}